### ISSUE TITLE
LIBUSB::ERROR_ACCESS in libusb_claim_interface

### ISSUE THREAD

**Issue by StephenFiser** [larskanis/libusb#26]
Hi :)

I'm attempting to stream data from an AIS receiver (antenna) - never done anything with USB before.

I've tried everything I can think of, and I keep getting **LIBUSB::ERROR_ACCESS in libusb_claim_interface** when I call open_interface(0).

Is there something obvious I can try?

Apologies if that's too vague. New to this side of dev.

**Comment by larskanis** [comment]
Check the permissions of the USB device. See http://www.rubydoc.info/gems/libusb/LIBUSB%2FDevice:open

**Comment by larskanis** [comment]
Closing with the hope, it is fixed.
