### ISSUE TITLE
LIBUSB::ERROR_ACCESS in Mac OS X

### ISSUE THREAD

**Issue by Benratelade** [larskanis/libusb#39]
Hi there, 

I was following the README file to try to interact with an audio interface connected via USB, on Mac OS X. 

Whenever I try to interact with a device, I get: `LIBUSB::ERROR_ACCESS`, for example: 
```ruby
device_handle.detach_kernel_driver(0)
LIBUSB::ERROR_ACCESS in libusb_detach_kernel_driver (LIBUSB::ERROR_ACCESS)
        from libusb-0.6.4/lib/libusb/dev_handle.rb:273:in `detach_kernel_driver'
```

My guess is that I don't have proper permissions (based on the docs: https://github.com/larskanis/libusb/blob/165bff575c92325e6afb4687de9bdea30c26d886/lib/libusb/device.rb#L51). 

However, my understanding is that there is no entry in /dev or anywhere in Mac OS that would make this possible. 

So my question is: is it even possible to process packets from a USB device in Mac OS X with libusb, or am I out of luck? 

Some environment info: 
libusb `1.0.26` installed with `brew install libusb`.
ruby `3.1.2`, on Mac OS X Ventura `13.3.1`.

**Comment by larskanis** [comment]
I don't know Macos well enough to give a specific answer. Just some ideas:

- I know from reading, that USB-HID devices are not easily accessible through libusb on Macos. These type of devices should be used through libhid instead.
- libusb for Ruby is just a wrapper around the C based libusb library. You can google for `LIBUSB_ERROR_ACCESS` to get some help.
