### ISSUE TITLE
[Question] Emulate a USB drive

### ISSUE THREAD

**Issue by rpbaltazar** [larskanis/libusb#40]
I was thinking of making an experiment and for that I thought I'd need to emulate a USB drive. Reading through what I found so far, this library would allow me to communicate with it but I can't find any documentation (or even feasibility) on doing so. Since you've worked on usb comm thought would be worth to ask.
Do you have any pointers?

**Comment by larskanis** [comment]
This library is only about communication with USB devices. See also #29
