### ISSUE TITLE
Broken backwards compatibility

### ISSUE THREAD

**Issue by xuijuthub** [larskanis/libusb#50]
README.md: `libusb C-library version 1.0.8 or any newer version`
but running example written in synopsis section and `rake test` uses `libusb_set_log_cb` and makes it crash as
```
TestLibusbGc#test_descriptors = <internal:gc>:34: warning: Exception in finalizer #<Method: #<FFI::Pointer address=0x00003f1adb34fe20>.free_struct(id) /home/user/testing/libusb/lib/libusb/context_reference.rb:20>
/home/user/testing/libusb/lib/libusb/context.rb:143:in `free_context': undefined method `libusb_set_log_cb' for LIBUSB::Call:Module (NoMethodError)

            Call.libusb_set_log_cb(self, nil, LOG_CB_CONTEXT)
                ^^^^^^^^^^^^^^^^^^
Did you mean?  libusb_set_debug
```
It's an issue on FreeBSD 14.1-RELEASE, as it has API compatibility up to 1.0.13, with 1.0.16 not fully implemented yet (https://github.com/freebsd/freebsd-src/commit/5654b42142e1f689b26d405c90379b85f22349a0).

**Comment by larskanis** [comment]
Thanks for reporting! Fixed in libusb-0.7.2.
